- set_fact:
    elastic_version: 2.3.1
- set_fact:
    elastic_distrname: "elasticsearch-{{ elastic_version }}"

# Ansible in Centos-7.2 is 1.9 So we cannot pass url to `unarchive` module
- name: Download elastic sources
  get_url:
    url: "https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/{{ elastic_version }}/{{ elastic_distrname }}.tar.gz"
    dest: /tmp

- name: Fetch
  unarchive:
    # src: "https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/{{ elastic_version }}/{{ elastic_distrname }}.tar.gz"
    src: "/tmp/{{ elastic_distrname }}.tar.gz"
    dest: "{{ user_home }}"
    copy: no
    owner: "{{ user }}"
    group: "{{ user }}"
    creates: "{{ user_home }}/{{ elastic_distrname }}"

- name: Set PATH environment variable
  lineinfile:
    dest: '{{ zshrc }}'
    line: export PATH="$HOME/{{ elastic_distrname }}/bin:$PATH"
    state: present

# - name: Install plugins
#   elasticsearch_plugin:
#     name: "{{ item }}"
#     state: present
#     plugin_bin: "{{ user_home }}/{{ elastic_distrname }}/bin/plugin"
#     plugin_dir: "{{ user_home }}/{{ elastic_distrname }}/plugins"
#   with_items:
#     - analysis-phonetic
#     - analysis-icu

- name: Ensure plugins dir
  file:
    path: "{{ user_home }}/{{ elastic_distrname }}/plugins"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- name: Install plugins
  command: "{{ user_home }}/{{ elastic_distrname }}/bin/plugin install {{ item }}"
  ignore_errors: yes
  with_items:
    - analysis-phonetic
    - analysis-icu
