- set_fact:
    nodejs_distrname: "node-v5.7.0-linux-x64"

- name: Fetch
  unarchive:
    src: https://nodejs.org/dist/v5.7.0/{{ nodejs_distrname }}.tar.xz
    dest: "{{ user_home }}"
    copy: no
    owner: "{{ user }}"
    group: "{{ user }}"
    creates: "{{ user_home }}/{{ nodejs_distrname }}"

- name: Set PATH environment variable
  lineinfile:
    dest: '{{ zshrc }}'
    line: export PATH="$HOME/{{ nodejs_distrname }}/bin:$PATH"
    state: present

- name: Install gulp
  npm:
    executable: "{{ user_home }}/{{ nodejs_distrname }}/bin/npm"
    global: yes
    state: present
    name: gulp
