- set_fact:
    nodejs_distrname: "node-v5.7.0-linux-x64"

# Ansible in Centos-7.2 is 1.9 So we cannot pass url to `unarchive` module
- name: Download node sources
  get_url:
    url: https://nodejs.org/dist/v5.7.0/{{ nodejs_distrname }}.tar.xz
    dest: /tmp

- name: Fetch
  unarchive:
    # src: https://nodejs.org/dist/v5.7.0/{{ nodejs_distrname }}.tar.xz
    src: /tmp/{{ nodejs_distrname }}.tar.xz
    dest: "{{ user_home }}"
    copy: no
    owner: "{{ user }}"
    group: "{{ user }}"
    creates: "{{ user_home }}/{{ nodejs_distrname }}"

- name: Set PATH environment variable
  lineinfile:
    dest: '{{ zshrc }}'
    line: export PATH="$HOME/{{ nodejs_distrname }}/bin:$PATH"
    state: present

- name: Install gulp
  npm:
    executable: "{{ user_home }}/{{ nodejs_distrname }}/bin/npm"
    global: yes
    state: present
    name: gulp
